my_file = open('text.txt', 'r')
content = my_file.read()
print('Содержимое файла: \n', content)
my_file = open('text.txt', 'r')
content = my_file.readlines()
print('Количество строк в файле - ', len(content))
my_file = open('text.txt', 'r')
content = my_file.readlines()
for i in range(len(content)):
    print('Окличество символов', {i + 1}, '- ой строки', len(content[i]))
my_file = open('text.txt', 'r')
content = my_file.read()
content = content.split()
print('Общее количество слов - ', len(content))
my_file.close()
